Write-Host "py-type setup helper"
Write-Host ""
Write-Host "TypeScript server:"
Write-Host "  cd apps/ts-mcp-server"
Write-Host "  pnpm install"
Write-Host "  pnpm dev"
Write-Host ""
Write-Host "Python server:"
Write-Host "  cd apps/py-mcp-server"
Write-Host "  py -m venv .venv"
Write-Host "  .venv\\Scripts\\Activate.ps1"
Write-Host "  pip install -e .[dev]"
Write-Host "  python -m py_mcp_server"
