Write-Host "Upload guide for py-type"
Write-Host ""
Write-Host "1. Make sure git is installed and available in PATH."
Write-Host "2. Create a new GitHub repository."
Write-Host "3. From C:\Users\ricky\Downloads\py-type run:"
Write-Host "   git init"
Write-Host "   git add ."
Write-Host "   git commit -m 'Initial py-type MCP platform'"
Write-Host "   git branch -M main"
Write-Host "   git remote add origin <your-repo-url>"
Write-Host "   git push -u origin main"
Write-Host ""
Write-Host "If you only need a package first, run:"
Write-Host "   pnpm package:release"
